### ISSUE TITLE
Unit 10 GitHub Basics Course to be completed

### ISSUE THREAD

**Issue by tamarabuilds** [tamarabuilds/fsjs-techdegree-project-files-unit10#2]
## TODO

*Courses left to complete in GitHub Basics Course*
* [x] Working by yourself
* [x] Working on a team
* [x] Create a web presense on GitHub
* [ ] Get involved in Open Source

🎉  🙆‍♀️  🎊
